# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_metric_record'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='records',
        ),
    ]
